spring.application.name=gym-app
server.port=8080
# ===============================
# MAIL CONFIG - MAILTRAP (DEV)
# ===============================

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=de840041887484
spring.mail.password=****12ef

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.default-encoding=UTF-8