spring.application.name=gym-app
server.port=8080
# ===============================
# MAIL CONFIG - MAILTRAP (DEV)
# ===============================

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=de840041887484
spring.mail.password=****12ef

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.default-encoding=UTF-8

# ===== DEBUG TEMPORAL =====
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.root=ERROR
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=on_param

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true